export const ALL_PRODUCT_REQUESTS = 'ALL_PRODUCT_REQUESTS'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAILURE = 'ALL_PRODUCT_FAILURE'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'

export const GET_PRODUCT_BY_CATEGORY_REQUEST = 'GET_PRODUCT_BY_CATEGORY_REQUEST';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = 'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAILURE = 'GET_PRODUCT_BY_CATEGORY_FAILURE';

export const ADMIN_PRODUCT_REQUESTS = 'ADMIN_PRODUCT_REQUESTS'
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS'
export const ADMIN_PRODUCT_FAILURE = 'ADMIN_PRODUCT_FAILURE'

export const NEW_PRODUCT_REQUESTS = 'NEW_PRODUCT_REQUESTS'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAILURE = 'NEW_PRODUCT_FAILURE' 
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'

export const UPDATE_PRODUCT_REQUESTS = 'UPDATE_PRODUCT_REQUESTS'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE' 
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'

export const DELETE_PRODUCT_REQUESTS = 'DELETE_PRODUCT_REQUESTS'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE' 
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'