export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUESTS'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_FAILURE = 'NEW_REVIEW_FAILURE' 
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'

export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUESTS'
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE' 

export const DELETE_REVIEW_REQUESTS = 'DELETE_REVIEW_REQUESTS'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE' 
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'